"""Add reservation policy and amount to wallet

Revision ID: 7140aa94cc8a
Revises: e4f8a9b2c1d3
Create Date: 2025-12-02 15:32:23.374120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7140aa94cc8a'
down_revision = 'e4f8a9b2c1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prespolicy', sa.Enum('DISABLE', 'AMOUNT', 'PERCENT', name='payoutreservepolicy'), nullable=True))
        batch_op.add_column(sa.Column('presamount', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('presamount')
        batch_op.drop_column('prespolicy')

    # ### end Alembic commands ###
