"""Add fee policies

Revision ID: cd6076e578ca
Revises: 0319bf7b9426
Create Date: 2024-07-31 10:39:30.170808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6076e578ca'
down_revision = '0319bf7b9426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_fee', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('fee_policy', sa.Enum('NO_FEE', 'PERCENT_FEE', 'FIXED_FEE', 'PERCENT_OR_MINIMAL_FIXED_FEE', name='feecalculationpolicy'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_column('fee_policy')
        batch_op.drop_column('fixed_fee')

    # ### end Alembic commands ###
